#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.
setbg.sh &              # set the background
bar.sh &                # lunch statusbar (dwm)
#poly-launch.sh &        # launch the statusbar

autostart="mpd picom dunst unclutter pipewire"
for program in $autostart; do
  pidof -s "$program" || setsid -f "$program"
done >/dev/null 2>&1

sleep 2 && xrandr --output HDMI1 --left-of eDP1
